# -*- coding: utf-8 -*-
"""main(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ceMsliT_oCKAV5BqxVNSrX97jnV_e3V1
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Definir una función para generar datos simulados
def generar_datos_simulados(cantidad_datos):
    np.random.seed(42)
    edad = np.random.randint(18, 80, cantidad_datos)
    peso = np.random.normal(70, 15, cantidad_datos)
    altura = np.random.normal(170, 10, cantidad_datos)
    enfermedad = np.random.choice([0, 1], cantidad_datos, p=[0.95, 0.05])  # 5% de probabilidad de tener la enfermedad
    data = {'Edad': edad, 'Peso': peso, 'Altura': altura, 'Enfermedad_Cronica': enfermedad}
    return pd.DataFrame(data)

# Función para entrenar el modelo y devolverlo
def entrenar_modelo(datos):
    X = datos[['Edad', 'Peso', 'Altura']]
    y = datos['Enfermedad_Cronica']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)
    return model, X_test, y_test

# Función para predecir enfermedades crónicas
def predecir_enfermedades(modelo, datos):
    X_test = datos[['Edad', 'Peso', 'Altura']]
    y_test = datos['Enfermedad_Cronica']
    y_pred = modelo.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    matrix = confusion_matrix(y_test, y_pred)
    return accuracy, report, matrix

# Configurar la aplicación de Streamlit
def main():
    st.title("Aplicación de Predicción de Enfermedades Crónicas")

    cantidad_datos = st.slider("Cantidad de Datos Simulados", 100, 2000, 500, step=100)
    datos_simulados = generar_datos_simulados(cantidad_datos)

    st.subheader("Datos Simulados:")
    st.write(datos_simulados)

    if st.button("Entrenar Modelo y Predecir"):
        st.write("Entrenando el modelo...")
        model, X_test, y_test = entrenar_modelo(datos_simulados)
        accuracy, report, matrix = predecir_enfermedades(model, datos_simulados)

        st.write(f"Accuracy del modelo: {accuracy:.2f}")
        st.write("Reporte de Clasificación:")
        st.write(report)

        # Mostrar histogramas de Edad, Peso y Altura
        st.subheader("Histogramas:")
        plt.figure(figsize=(8, 6))
        plt.hist(datos_simulados['Edad'], bins=30, alpha=0.7, label='Edad')
        plt.hist(datos_simulados['Peso'], bins=30, alpha=0.7, label='Peso')
        plt.hist(datos_simulados['Altura'], bins=30, alpha=0.7, label='Altura')
        plt.legend()
        st.pyplot()

        # Mostrar matriz de confusión
        st.subheader("Matriz de Confusión:")
        sns.heatmap(matrix, annot=True, fmt='d', cmap='Blues')
        st.pyplot()

# Ejecutar la aplicación
if __name__ == "__main__":
    main()